// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Concert documents
 */
interface ConcertDocumentData {
  /**
   * Venue field in *Concert*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: concert.venue
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  venue: prismic.KeyTextField;

  /**
   * Location field in *Concert*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: concert.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  location: prismic.KeyTextField;

  /**
   * Date field in *Concert*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: concert.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Link field in *Concert*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: concert.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Featured field in *Concert*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: concert.featured
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  featured: prismic.BooleanField;
}

/**
 * Concert document from Prismic
 *
 * - **API ID**: `concert`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ConcertDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ConcertDocumentData>,
    'concert',
    Lang
  >;

/**
 * Item in *MediaSection → Media*
 */
export interface MediaSectionDocumentDataMediaItem {
  /**
   * Title field in *MediaSection → Media*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_section.media[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * File field in *MediaSection → Media*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: media_section.media[].file
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  file: prismic.LinkToMediaField;

  /**
   * Media Type field in *MediaSection → Media*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: media_section.media[].media_type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  media_type: prismic.SelectField<'Audio' | 'Video'>;

  /**
   * Poster field in *MediaSection → Media*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: media_section.media[].poster
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  poster: prismic.ImageField<never>;
}

/**
 * Content for MediaSection documents
 */
interface MediaSectionDocumentData {
  /**
   * Title field in *MediaSection*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_section.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *MediaSection*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_section.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Media field in *MediaSection*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: media_section.media[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  media: prismic.GroupField<Simplify<MediaSectionDocumentDataMediaItem>>;
}

/**
 * MediaSection document from Prismic
 *
 * - **API ID**: `media_section`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MediaSectionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<MediaSectionDocumentData>,
    'media_section',
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | ContactSlice
  | DocumentLinkSlice
  | RevealedContentSlice
  | OverlaySectionSlice
  | ReelSlice
  | HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, 'page', Lang>;

export type AllDocumentTypes =
  | ConcertDocument
  | MediaSectionDocument
  | PageDocument;

/**
 * Primary content in *Contact → Primary*
 */
export interface ContactSliceDefaultPrimary {
  /**
   * Title field in *Contact → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Image field in *Contact → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Tint field in *Contact → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: none
   * - **API ID Path**: contact.primary.tint
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  tint: prismic.SelectField<'none' | 'primary' | 'secondary', 'filled'>;
}

/**
 * Default variation for Contact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ContactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Contact*
 */
type ContactSliceVariation = ContactSliceDefault;

/**
 * Contact Shared Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSlice = prismic.SharedSlice<
  'contact',
  ContactSliceVariation
>;

/**
 * Primary content in *DocumentLink → Primary*
 */
export interface DocumentLinkSliceDefaultPrimary {
  /**
   * Document field in *DocumentLink → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: document_link.primary.document
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  document: prismic.ContentRelationshipField;
}

/**
 * Default variation for DocumentLink Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DocumentLinkSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<DocumentLinkSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *DocumentLink*
 */
type DocumentLinkSliceVariation = DocumentLinkSliceDefault;

/**
 * DocumentLink Shared Slice
 *
 * - **API ID**: `document_link`
 * - **Description**: DocumentLink
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DocumentLinkSlice = prismic.SharedSlice<
  'document_link',
  DocumentLinkSliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Title field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<'16/9' | '9/16'>;

  /**
   * Tint field in *Hero → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: none
   * - **API ID Path**: hero.primary.tint
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  tint: prismic.SelectField<'none' | 'primary' | 'secondary', 'filled'>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<'hero', HeroSliceVariation>;

/**
 * Primary content in *OverlaySection → Primary*
 */
export interface OverlaySectionSliceDefaultPrimary {
  /**
   * Title field in *OverlaySection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: overlay_section.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *OverlaySection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: overlay_section.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Image field in *OverlaySection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: overlay_section.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<'24/9' | '3/2'>;

  /**
   * Image Ratio field in *OverlaySection → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 24:9
   * - **API ID Path**: overlay_section.primary.image_ratio
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  image_ratio: prismic.SelectField<'24:9' | '3:2', 'filled'>;

  /**
   * Tint field in *OverlaySection → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: none
   * - **API ID Path**: overlay_section.primary.tint
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  tint: prismic.SelectField<'none' | 'primary' | 'secondary', 'filled'>;
}

/**
 * Default variation for OverlaySection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OverlaySectionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<OverlaySectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *OverlaySection*
 */
type OverlaySectionSliceVariation = OverlaySectionSliceDefault;

/**
 * OverlaySection Shared Slice
 *
 * - **API ID**: `overlay_section`
 * - **Description**: OverlaySection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OverlaySectionSlice = prismic.SharedSlice<
  'overlay_section',
  OverlaySectionSliceVariation
>;

/**
 * Primary content in *Reel → Items*
 */
export interface ReelSliceDefaultItem {
  /**
   * Image field in *Reel → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: reel.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<'2/3'>;
}

/**
 * Default variation for Reel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReelSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  Simplify<ReelSliceDefaultItem>
>;

/**
 * Slice variation for *Reel*
 */
type ReelSliceVariation = ReelSliceDefault;

/**
 * Reel Shared Slice
 *
 * - **API ID**: `reel`
 * - **Description**: Reel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReelSlice = prismic.SharedSlice<'reel', ReelSliceVariation>;

/**
 * Primary content in *RevealedContent → Primary*
 */
export interface RevealedContentSliceDefaultPrimary {
  /**
   * Title field in *RevealedContent → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: revealed_content.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Image field in *RevealedContent → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: revealed_content.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<'4/3' | '3/2'>;

  /**
   * Tint field in *RevealedContent → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: none
   * - **API ID Path**: revealed_content.primary.tint
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  tint: prismic.SelectField<'none' | 'primary' | 'secondary', 'filled'>;
}

/**
 * Primary content in *RevealedContent → Items*
 */
export interface RevealedContentSliceDefaultItem {
  /**
   * Content field in *RevealedContent → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: revealed_content.items[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RevealedContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RevealedContentSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<RevealedContentSliceDefaultPrimary>,
  Simplify<RevealedContentSliceDefaultItem>
>;

/**
 * Primary content in *RevealedContent → Primary*
 */
export interface RevealedContentSliceConcertPrimary {
  /**
   * Title field in *RevealedContent → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: revealed_content.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Image field in *RevealedContent → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: revealed_content.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<'4/3'>;

  /**
   * Tint field in *RevealedContent → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: none
   * - **API ID Path**: revealed_content.primary.tint
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  tint: prismic.SelectField<'none' | 'primary' | 'secondary', 'filled'>;
}

/**
 * Concert variation for RevealedContent Slice
 *
 * - **API ID**: `concert`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RevealedContentSliceConcert = prismic.SharedSliceVariation<
  'concert',
  Simplify<RevealedContentSliceConcertPrimary>,
  never
>;

/**
 * Slice variation for *RevealedContent*
 */
type RevealedContentSliceVariation =
  | RevealedContentSliceDefault
  | RevealedContentSliceConcert;

/**
 * RevealedContent Shared Slice
 *
 * - **API ID**: `revealed_content`
 * - **Description**: RevealedContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RevealedContentSlice = prismic.SharedSlice<
  'revealed_content',
  RevealedContentSliceVariation
>;

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ConcertDocument,
      ConcertDocumentData,
      MediaSectionDocument,
      MediaSectionDocumentData,
      MediaSectionDocumentDataMediaItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      ContactSlice,
      ContactSliceDefaultPrimary,
      ContactSliceVariation,
      ContactSliceDefault,
      DocumentLinkSlice,
      DocumentLinkSliceDefaultPrimary,
      DocumentLinkSliceVariation,
      DocumentLinkSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      OverlaySectionSlice,
      OverlaySectionSliceDefaultPrimary,
      OverlaySectionSliceVariation,
      OverlaySectionSliceDefault,
      ReelSlice,
      ReelSliceDefaultItem,
      ReelSliceVariation,
      ReelSliceDefault,
      RevealedContentSlice,
      RevealedContentSliceDefaultPrimary,
      RevealedContentSliceDefaultItem,
      RevealedContentSliceConcertPrimary,
      RevealedContentSliceVariation,
      RevealedContentSliceDefault,
      RevealedContentSliceConcert,
    };
  }
}
