// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  contact: dynamic(() => import('./Contact')),
  document_link: dynamic(() => import('./DocumentLink')),
  hero: dynamic(() => import('./Hero')),
  overlay_section: dynamic(() => import('./OverlaySection')),
  reel: dynamic(() => import('./Reel')),
  revealed_content: dynamic(() => import('./RevealedContent')),
};
