// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  hero: dynamic(() => import('./Hero')),
  media: dynamic(() => import('./Media')),
  overlay_section: dynamic(() => import('./OverlaySection')),
  reel: dynamic(() => import('./Reel')),
  revealed_content: dynamic(() => import('./RevealedContent')),
};
